version: "3.9"
services:
  redis:
    image: "docker.io/bitnami/redis:6.2.6-debian-10-r53"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/bitnami/redis/data"

  mongodb:
    image: "bitnami/mongodb:latest"
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'

volumes:
  redis_data:
    driver: local
  mongodb_data:
    driver: local