FROM python:3.8-buster

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY ./features ./features
COPY ./sdk ./sdk
COPY ./util ./util
COPY ./schedule.py ./schedule.py

CMD [ "python3", "schedule.py" ]