apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
spec:
  selector:
    matchLabels:
      app: app
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: python-socketio
          image: '{{ .Values.werf.image.app }}'
          workingDir: /app
          env:
            - name: EK_PLUGIN_ID
              value: {{ .Chart.Name }}
            - name: MONGO_URI
              value: "{{ .Values.mongodb.uri }}"
            - name: MONGO_DB_NAME
              value: "{{ .Values.mongodb.dbName }}"
            - name: ETHERSCAN_API_KEY
              value: "{{ .Values.etherscan.apiKey }}"
            - name: ETHERSCAN_BASE_URL
              value: "{{ .Values.etherscan.baseUrl }}"
            - name: WEB3_PROVIDER_URL
              value: "{{ .Values.web3.providerUrl }}"
            - name: REDIS_URI
              value: 'redis://{{ .Release.Name }}-redis-master'
          ports:
            - containerPort: 3001
              protocol: TCP
