apiVersion: apps/v1
kind: Deployment
metadata:
  name: listener-deploy
spec:
  selector:
    matchLabels:
      app: listener
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: listener
    spec:
      containers:
        - name: python
          image: '{{ .Values.werf.image.listener }}'
          workingDir: /app
          env:
            - name: WEB3_PROVIDER_URL
              value: "{{ .Values.web3.providerUrl }}"
            - name: REDIS_URI
              value: 'redis://{{ .Release.Name }}-redis-master'
            - name: DISCORD_BASE_URL
              value: "{{ .Values.discord.baseUrl }}"
            - name: DISCORD_CHANNEL_ID
              value: '{{ eq .Values.werf.env "staging" | ternary .Values.discord.channelId.staging .Values.discord.channelId._default }}'
