apiVersion: batch/v1
kind: CronJob
metadata:
  name: schedule-job
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            job: schedule
        spec:
          restartPolicy: Never
          containers:
            - name: python
              image: "{{ .Values.werf.image.schedule }}"
              workingDir: /app
              env:
                - name: REDIS_HOST
                  value: '{{ .Release.Name }}-redis-master'
